/**
 * SumSub API types.
 *
 * Derived from the OpenAPI spec at https://api.sumsub.com/openapi.json
 * and the official docs at https://docs.sumsub.com.
 */

// ---------------------------------------------------------------------------
// Environment + config
// ---------------------------------------------------------------------------

export type SumsubEnvironment = "sandbox" | "production";

export interface SumsubClientConfig {
  /** App Token from SumSub dashboard (sandbox tokens start with `sbx:`). */
  appToken: string;
  /** Secret key paired with the app token. */
  secretKey: string;
  /** Defaults to `"sandbox"` (D-005). */
  env?: SumsubEnvironment;
  /** Override the base URL. Defaults to `https://api.sumsub.com`. */
  baseUrl?: string;
}

// ---------------------------------------------------------------------------
// Applicant
// ---------------------------------------------------------------------------

export type ApplicantReviewStatus =
  | "init"
  | "pending"
  | "prechecked"
  | "queued"
  | "completed"
  | "onHold";

export type ApplicantReviewAnswer =
  | "GREEN"
  | "RED";

export interface ApplicantReviewResult {
  reviewAnswer?: ApplicantReviewAnswer;
  rejectLabels?: string[];
  reviewRejectType?: "FINAL" | "RETRY";
  moderationComment?: string;
  clientComment?: string;
}

export interface ApplicantReview {
  reviewId?: string;
  attemptId?: string;
  attemptCnt?: number;
  reviewStatus?: ApplicantReviewStatus;
  reviewResult?: ApplicantReviewResult;
  createDate?: string;
  reviewDate?: string;
  priority?: number;
}

export interface ApplicantFixedInfo {
  firstName?: string;
  lastName?: string;
  middleName?: string;
  dob?: string;
  gender?: string;
  country?: string;
  nationality?: string;
  placeOfBirth?: string;
}

export interface ApplicantInfo extends ApplicantFixedInfo {
  phone?: string;
  email?: string;
  addresses?: ApplicantAddress[];
}

export interface ApplicantAddress {
  country?: string;
  town?: string;
  street?: string;
  subStreet?: string;
  postCode?: string;
  state?: string;
  buildingNumber?: string;
  flatNumber?: string;
}

export interface Applicant {
  id: string;
  createdAt?: string;
  inspectionId?: string;
  externalUserId?: string;
  fixedInfo?: ApplicantFixedInfo;
  info?: ApplicantInfo;
  review?: ApplicantReview;
  type?: string;
  levelName?: string;
  sandboxMode?: boolean;
  [key: string]: unknown;
}

export interface CreateApplicantRequest {
  externalUserId: string;
  levelName: string;
  info?: ApplicantInfo;
  fixedInfo?: ApplicantFixedInfo;
  [key: string]: unknown;
}

// ---------------------------------------------------------------------------
// Access tokens
// ---------------------------------------------------------------------------

export interface AccessToken {
  token: string;
  userId?: string;
}

export interface GenerateAccessTokenRequest {
  /** SumSub applicant id or external user id. */
  userId: string;
  /** Verification level name. */
  levelName: string;
  /** TTL in seconds (default 600). */
  ttlInSecs?: number;
}

export interface GenerateShareTokenRequest {
  /** The applicant id whose identity data will be shared. */
  applicantId: string;
  /** Verification level to share against. */
  levelName?: string;
}

// ---------------------------------------------------------------------------
// Reusable identity (reliance / token sharing)
// ---------------------------------------------------------------------------

export interface ReuseIdentityRequest {
  /** Share token generated by the originating SumSub account. */
  shareToken: string;
  /** Verification level in the receiving account. */
  levelName: string;
  /** External user id to assign to the new applicant. */
  userId?: string;
  /** Source key for applicant routing. */
  sourceKey?: string;
}

export interface ReuseIdentityPreview {
  id: string;
  info?: ApplicantInfo;
  fixedInfo?: ApplicantFixedInfo;
  review?: ApplicantReview;
  [key: string]: unknown;
}

// ---------------------------------------------------------------------------
// Webhooks
// ---------------------------------------------------------------------------

export type SumsubWebhookType =
  | "applicantReviewed"
  | "applicantPending"
  | "applicantCreated"
  | "applicantOnHold"
  | "applicantActionPending"
  | "applicantActionReviewed"
  | "applicantActionOnHold"
  | "applicantReset"
  | "applicantPersonalInfoChanged"
  | "applicantPrechecked"
  | "videoIdentStatusChanged"
  | "applicantDeleted"
  | "applicantLevelChanged"
  | "applicantWorkflowCompleted"
  | string;

export interface SumsubWebhookPayload {
  applicantId: string;
  inspectionId?: string;
  correlationId?: string;
  externalUserId?: string;
  type: SumsubWebhookType;
  reviewResult?: ApplicantReviewResult;
  reviewStatus?: ApplicantReviewStatus;
  createdAtMs?: string;
  sandboxMode?: boolean;
  [key: string]: unknown;
}

// ---------------------------------------------------------------------------
// Client interface
// ---------------------------------------------------------------------------

export interface ISumsubClient {
  /** Create a new applicant. */
  createApplicant(request: CreateApplicantRequest): Promise<Applicant>;

  /** Get an applicant by SumSub id. */
  getApplicant(applicantId: string): Promise<Applicant>;

  /** Get an applicant by external user id. */
  getApplicantByExternalId(externalUserId: string): Promise<Applicant>;

  /** Get the verification status of an applicant. */
  getApplicantStatus(applicantId: string): Promise<ApplicantReview>;

  /** Generate an SDK access token for client-side verification. */
  generateAccessToken(request: GenerateAccessTokenRequest): Promise<AccessToken>;

  /** Generate a share token for reliance KYC / token sharing. */
  generateShareToken(request: GenerateShareTokenRequest): Promise<AccessToken>;

  /**
   * Consume a share token to create an applicant from shared identity data.
   * This is the receiving side of SumSub reliance KYC.
   */
  reuseIdentity(request: ReuseIdentityRequest): Promise<Applicant>;

  /** Preview what data a share token contains before consuming it. */
  previewReuseIdentity(request: ReuseIdentityRequest): Promise<ReuseIdentityPreview>;

  /** Reset an applicant's verification (sandbox). */
  resetApplicant(applicantId: string): Promise<void>;
}
