import type { CheckoutExecutionState, CheckoutSettlementState } from "@dynamic-labs-sdk/client";
import type { CheckoutTransaction } from "./index";
import type { ExecutionUpdate } from "../lib/types";

export interface MapContext {
  /** True iff the source token differs from the settlement token (or chain). */
  needsConversion: boolean;
  /** Total UI steps as generated by generateTransactionSteps. */
  totalSteps: number;
  /** True iff source chain ≠ destination chain. Forwarded verbatim to `ExecutionUpdate.isCrossChain` on the bridging arm; callers must pass `true` whenever bridging is possible. */
  isCrossChain: boolean;
  /** UI step index to mark FAILED on terminal failure; defaults to 0. */
  currentStepIndex?: number;
}

// Narrowing helpers — cast the enum-typed fields to the string-union aliases
// so we can compare against plain string literals without importing the enum
// class from the transitive @dynamic-labs/sdk-api-core package.
const execState = (t: CheckoutTransaction): CheckoutExecutionState =>
  t.executionState as unknown as CheckoutExecutionState;
const settlState = (t: CheckoutTransaction): CheckoutSettlementState =>
  t.settlementState as unknown as CheckoutSettlementState;

/**
 * Translate a Dynamic CheckoutTransaction state snapshot into the
 * ExecutionUpdate shape the existing payment-widget UI already consumes.
 *
 * This function is pure: same inputs → same output. All UI step-list logic
 * lives in components/payment-modal/transaction-progress-screen.tsx; this
 * mapper only decides which step is active and what status it carries.
 */
export function mapTransactionToUpdate(
  transaction: CheckoutTransaction,
  ctx: MapContext,
): ExecutionUpdate {
  const { needsConversion, totalSteps, isCrossChain, currentStepIndex = 0 } = ctx;
  const lastStep = Math.max(0, totalSteps - 1);
  const baseProcess: ExecutionUpdate["processType"] = needsConversion
    ? "SWAP"
    : "TRANSFER";

  const exec = execState(transaction);
  const sett = settlState(transaction);

  // Terminal failures take priority — short-circuit before reading other state.
  if (
    exec === "failed" ||
    exec === "expired" ||
    exec === "cancelled" ||
    sett === "failed"
  ) {
    return {
      stepIndex: currentStepIndex,
      totalSteps,
      status: "FAILED",
      processType: baseProcess,
    };
  }

  // Settlement state takes precedence over execution state once we're past broadcast.
  if (exec === "source_confirmed") {
    switch (sett) {
      case "bridging":
        return {
          stepIndex: Math.min(2, lastStep),
          totalSteps,
          status: "RUNNING",
          processType: "CROSS_CHAIN",
          isCrossChain,
          isBridging: true,
          txHash: transaction.txHash,
        };
      case "swapping":
        return {
          stepIndex: lastStep,
          totalSteps,
          status: "RUNNING",
          processType: "SWAP",
          txHash: transaction.txHash,
        };
      case "settling":
        return {
          stepIndex: lastStep,
          totalSteps,
          status: "RUNNING",
          processType: "RECEIVING",
          txHash: transaction.txHash,
        };
      case "completed":
        return {
          stepIndex: lastStep,
          totalSteps,
          status: "DONE",
          processType: "RECEIVING",
          txHash: transaction.txHash,
        };
      // Any other settlement state (routing, none, or a future value) falls through
      // to the outer switch's "source_confirmed" arm below, which returns RUNNING step 1.
    }
  }

  // Execution state drives early steps.
  switch (exec) {
    case "initiated":
    case "source_attached":
    case "quoted":
      return {
        stepIndex: 0,
        totalSteps,
        status: "PENDING",
        processType: baseProcess,
      };
    case "signing":
      return {
        stepIndex: 0,
        totalSteps,
        status: "ACTION_REQUIRED",
        processType: baseProcess,
      };
    // Reached by `broadcasted` directly, and by `source_confirmed` falling through
    // from the block above when settlementState is `routing`, `none`, or an
    // unrecognized future value.
    case "broadcasted":
    case "source_confirmed":
      return {
        stepIndex: 1,
        totalSteps,
        status: "RUNNING",
        processType: baseProcess,
        txHash: transaction.txHash,
      };
  }

  // Defensive fallback — shouldn't happen if SDK is current.
  return {
    stepIndex: currentStepIndex,
    totalSteps,
    status: "PENDING",
    processType: baseProcess,
  };
}
