import type { CheckoutExecutionState, CheckoutSettlementState } from "@dynamic-labs-sdk/client";
import type { CheckoutTransaction } from "./index";
import type { ExecutionUpdate } from "../lib/types";

export interface MapContext {
  /** True iff the source token differs from the settlement token (or chain). */
  needsConversion: boolean;
  /** Total UI steps as generated by generateTransactionSteps. */
  totalSteps: number;
  /** True iff source chain ≠ destination chain. Forwarded verbatim to `ExecutionUpdate.isCrossChain` on the bridging arm; callers must pass `true` whenever bridging is possible. */
  isCrossChain: boolean;
  /** UI step index to mark FAILED on terminal failure; defaults to 0. */
  currentStepIndex?: number;
}

// Narrowing helpers — cast the enum-typed fields to the string-union aliases
// so we can compare against plain string literals without importing the enum
// class from the transitive @dynamic-labs/sdk-api-core package.
const execState = (t: CheckoutTransaction): CheckoutExecutionState =>
  t.executionState as unknown as CheckoutExecutionState;
const settlState = (t: CheckoutTransaction): CheckoutSettlementState =>
  t.settlementState as unknown as CheckoutSettlementState;

/**
 * Terminal *failure* states — `failed`/`expired`/`cancelled` on the
 * execution axis OR `failed` on the settlement axis. Single source of
 * truth so `mapTransactionToUpdate`, `useCheckoutFlow.submit`, and
 * `PaymentWidget`'s defensive post-submit check all agree.
 */
export function isFailedTerminal(t: CheckoutTransaction): boolean {
  const exec = execState(t);
  const sett = settlState(t);
  return (
    exec === "failed" ||
    exec === "expired" ||
    exec === "cancelled" ||
    sett === "failed"
  );
}

/**
 * Shape of the `failure` discriminator that Dynamic's API attaches to
 * a CheckoutTransaction when the bridge / settlement engine rejects
 * the source on-chain tx (e.g. `BRIDGE_FAILED / source_confirm`). The
 * SDK's `CheckoutTransaction` type doesn't model this field yet (as of
 * 1.3.0), so callers have to lift it via a typed accessor instead of
 * an open `as unknown as` cast each time.
 */
export interface CheckoutFailureInfo {
  code?: string;
  message?: string;
  category?: string;
  stage?: string;
}

/**
 * Lift the `failure` blob off a CheckoutTransaction without an ad-hoc
 * cast at each site. Returns `null` when the field isn't populated
 * (success case or non-terminal). Use {@link extractFailureMessage}
 * for the human-readable string variant.
 */
export function extractFailureInfo(
  t: CheckoutTransaction,
): CheckoutFailureInfo | null {
  const f = (t as unknown as { failure?: CheckoutFailureInfo }).failure;
  return f ?? null;
}

/**
 * Best-effort human-readable failure message. Falls back to the
 * failure code, then to a generic message stamped with the execution
 * state, so the UI never renders a blank "Transaction failed" without
 * context.
 */
export function extractFailureMessage(t: CheckoutTransaction): string {
  const failure = extractFailureInfo(t);
  if (failure?.message) return failure.message;
  if (failure?.code) return `Transaction failed: ${failure.code}`;
  const exec = execState(t);
  return `Transaction failed (executionState=${exec || "unknown"})`;
}

/**
 * Translate a Dynamic CheckoutTransaction state snapshot into the
 * ExecutionUpdate shape the existing payment-widget UI already consumes.
 *
 * This function is pure: same inputs → same output. All UI step-list logic
 * lives in components/payment-modal/transaction-progress-screen.tsx; this
 * mapper only decides which step is active and what status it carries.
 */
export function mapTransactionToUpdate(
  transaction: CheckoutTransaction,
  ctx: MapContext,
): ExecutionUpdate {
  const { needsConversion, totalSteps, isCrossChain, currentStepIndex = 0 } = ctx;
  const lastStep = Math.max(0, totalSteps - 1);
  const baseProcess: ExecutionUpdate["processType"] = needsConversion
    ? "SWAP"
    : "TRANSFER";

  const exec = execState(transaction);
  const sett = settlState(transaction);

  // Terminal failures take priority — short-circuit before reading other state.
  if (isFailedTerminal(transaction)) {
    return {
      stepIndex: currentStepIndex,
      totalSteps,
      status: "FAILED",
      processType: baseProcess,
    };
  }

  // Settlement state takes precedence over execution state once we're past broadcast.
  if (exec === "source_confirmed") {
    switch (sett) {
      case "bridging":
        return {
          stepIndex: Math.min(2, lastStep),
          totalSteps,
          status: "RUNNING",
          processType: "CROSS_CHAIN",
          isCrossChain,
          isBridging: true,
          txHash: transaction.txHash,
        };
      case "swapping":
        return {
          stepIndex: lastStep,
          totalSteps,
          status: "RUNNING",
          processType: "SWAP",
          txHash: transaction.txHash,
        };
      case "settling":
        return {
          stepIndex: lastStep,
          totalSteps,
          status: "RUNNING",
          processType: "RECEIVING",
          txHash: transaction.txHash,
        };
      case "completed":
        return {
          stepIndex: lastStep,
          totalSteps,
          status: "DONE",
          processType: "RECEIVING",
          txHash: transaction.txHash,
        };
      // Any other settlement state (routing, none, or a future value) falls through
      // to the outer switch's "source_confirmed" arm below, which returns RUNNING step 1.
    }
  }

  // Execution state drives early steps.
  switch (exec) {
    case "initiated":
    case "source_attached":
    case "quoted":
      return {
        stepIndex: 0,
        totalSteps,
        status: "PENDING",
        processType: baseProcess,
      };
    case "signing":
      return {
        stepIndex: 0,
        totalSteps,
        status: "ACTION_REQUIRED",
        processType: baseProcess,
      };
    // Reached by `broadcasted` directly, and by `source_confirmed` falling through
    // from the block above when settlementState is `routing`, `none`, or an
    // unrecognized future value.
    case "broadcasted":
    case "source_confirmed":
      return {
        stepIndex: 1,
        totalSteps,
        status: "RUNNING",
        processType: baseProcess,
        txHash: transaction.txHash,
      };
  }

  // Defensive fallback — shouldn't happen if SDK is current.
  return {
    stepIndex: currentStepIndex,
    totalSteps,
    status: "PENDING",
    processType: baseProcess,
  };
}
