import path from "node:path";
import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  // pnpm monorepo — tell Next.js where the workspace root is so file
  // tracing can follow symlinks into ../../node_modules/.pnpm/...
  outputFileTracingRoot: path.join(__dirname, "../../"),
  // Bundle the Prisma Linux query engine into the serverless function
  // payload. The binary is generated by `prisma generate` (postinstall)
  // when `binaryTargets` in schema.prisma includes `rhel-openssl-3.0.x`.
  // Without this trace hint, Next.js drops the .so.node file from the
  // function bundle and the dashboard 500s at runtime.
  outputFileTracingIncludes: {
    "/**/*": [
      "../../node_modules/.pnpm/@prisma+client*/node_modules/.prisma/client/libquery_engine-*",
    ],
  },
  images: {
    remotePatterns: [
      {
        protocol: "https",
        hostname: "lh3.googleusercontent.com",
        pathname: "/**",
      },
    ],
  },
  async redirects() {
    return [
      // Operators have `/brands` bookmarks and links out in the wild; 308
      // (permanent) keeps them working and tells crawlers/clients to update
      // to the current path.
      {
        source: "/brands",
        destination: "/dashboard",
        permanent: true,
      },
      {
        source: "/brands/:path*",
        destination: "/dashboard/prospects/:path*",
        permanent: true,
      },
      // No known consumer references the public brand-profile API route
      // today (demo apps fetch resolved themes via DemoConfig, D-028), but
      // redirecting costs nothing and protects against an out-of-repo caller.
      {
        source: "/api/brands/:path*",
        destination: "/api/prospects/:path*",
        permanent: true,
      },
    ];
  },
  // API CORS is owned entirely by src/middleware.ts - a single authority that
  // wildcards general API routes but lets the tracker endpoints
  // (/api/events, /api/share/context) enforce their exact-origin allowlist.
};

export default nextConfig;
