import path from "node:path";
import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  // pnpm monorepo — tell Next.js where the workspace root is so file
  // tracing can follow symlinks into ../../node_modules/.pnpm/...
  outputFileTracingRoot: path.join(__dirname, "../../"),
  // Bundle the Prisma Linux query engine into the serverless function
  // payload. The binary is generated by `prisma generate` (postinstall)
  // when `binaryTargets` in schema.prisma includes `rhel-openssl-3.0.x`.
  // Without this trace hint, Next.js drops the .so.node file from the
  // function bundle and the dashboard 500s at runtime.
  outputFileTracingIncludes: {
    "/**/*": [
      "../../node_modules/.pnpm/@prisma+client*/node_modules/.prisma/client/libquery_engine-*",
    ],
  },
  images: {
    remotePatterns: [
      {
        protocol: "https",
        hostname: "lh3.googleusercontent.com",
        pathname: "/**",
      },
    ],
  },
  async headers() {
    return [
      {
        // Apply CORS headers to all API routes
        source: "/api/:path*",
        headers: [
          { key: "Access-Control-Allow-Credentials", value: "true" },
          { key: "Access-Control-Allow-Origin", value: "*" },
          {
            key: "Access-Control-Allow-Methods",
            value: "GET, POST, PUT, PATCH, DELETE, OPTIONS",
          },
          {
            key: "Access-Control-Allow-Headers",
            value:
              "Content-Type, Authorization, x-dynamic-environment-id, X-CSRF-Token, X-Requested-With, Accept, Accept-Version, Content-Length, Content-MD5, Date, X-Api-Version",
          },
        ],
      },
    ];
  },
};

export default nextConfig;
