"use client";

/**
 * Client-boundary re-export for Droplet primitives. `@dynamic-labs-sdk/droplet`
 * ships without a `"use client"` directive but evaluates React context at module
 * scope (via Radix), which crashes when imported directly from a Server
 * Component. Importing through this shim turns each component into a client
 * reference, so server components stay server components.
 *
 * Single source for every new operator surface (GTM IA) and the public tree.
 */
export {
  Badge,
  Button,
  Card,
  CardContent,
  CardDescription,
  CardFooter,
  CardHeader,
  CardTitle,
  Input,
  Label,
  Textarea,
  Select,
  SelectContent,
  SelectGroup,
  SelectItem,
  SelectLabel,
  SelectTrigger,
  SelectValue,
  Table,
  TableBody,
  TableCaption,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
  Tabs,
  TabsContent,
  TabsList,
  TabsTrigger,
  Sheet,
  SheetClose,
  SheetContent,
  SheetDescription,
  SheetFooter,
  SheetHeader,
  SheetTitle,
  SheetTrigger,
  Dialog,
  DialogBody,
  DialogClose,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuLabel,
  DropdownMenuSeparator,
  DropdownMenuTrigger,
  Popover,
  PopoverContent,
  PopoverTrigger,
  Spinner,
  Avatar,
  AvatarFallback,
  AvatarImage,
  Separator,
  Skeleton,
  EmptyState,
  ScrollArea,
  MetricCard,
  SettingsSection,
  StatusBadge,
  Tooltip,
  TooltipContent,
  TooltipProvider,
  TooltipTrigger,
  Toaster,
  toast,
  UnsavedChangesBar,
} from "@dynamic-labs-sdk/droplet";
